### ISSUE TITLE
Error in windows 10 while opening zip

### ISSUE THREAD

**Issue by riazXrazor** [zanysoft/laravel-zip#15]
Hi, this is specific error only in windows 10  without winrar or 7zip, i am not sure why its happening.
![error](https://user-images.githubusercontent.com/13194363/51893903-505bba00-23cc-11e9-9f4d-022ed7d0f012.png)

**Comment by Tcheikovski** [comment]
I think that's because Windows 10's built-in ZIP utility is incompatible with all the encryption methods provided by PHP's ZipArchive() object (AES-128, 256 and friends)
The same error ocurred to me while I was trying to build my own Zip module on Laravel. The only solution I found is to exec() your server's zip utility (zip on linux, 7z on windows, etc)
